name: toni
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  provider: ^6.0.4
  shared_preferences: ^2.0.15
  google_fonts: ^3.0.1
  dio: ^4.0.6
  firebase_messaging: ^14.6.2
  firebase_core: ^2.13.1
  flutter_svg: ^2.0.5




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/
   - assets/icon/
